[package]
name = "drones-attack"
version = "0.1.0"
authors = ["sjbeskur <sam.beskur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
rodio = "0.14.0"
